# 指定Java的版本，高版本不需要指定
# -target 17
# 指定不打印有关配置中潜在错误或遗漏的注释
-dontnote
# proguard会对代码进行优化压缩，他会删除从未使用的类或者类成员变量等
-dontshrink
# 是否关闭字节码级别的优化，如果不开启则设置如下配置
-dontoptimize
# 混淆时不生成大小写混合的类名，默认是可以大小写混合
-dontusemixedcaseclassnames
# 对于类成员的命名的混淆采取唯一策略
-useuniqueclassmembernames
# Rename FXML files together with related views
-adaptresourcefilenames **.fxml,**.png,**.css,**.properties,**.json,**.js,**.xdb,**.txt,**.csv,**.dat
-adaptresourcefilecontents **.fxml
# 混淆类名之后，对使用Class.forName('className')之类的地方进行相应替代
-adaptclassstrings

# Save meta-data for stack traces
-printmapping out.map
-renamesourcefileattribute SourceFile
# 对异常、注解信息予以保留
-keepattributes Exceptions,InnerClasses,Signature,Deprecated,SourceFile,LineNumberTable,*Annotation*,EnclosingMethod
# 此选项将保存接口中的所有原始名称（不混淆）-->
-keepnames interface ** { *; }
# 此选项将保存所有软件包中的所有原始接口文件（不进行混淆）
#-keep interface * extends * { *; }
# 保留参数名，因为控制器，或者Mybatis等接口的参数如果混淆会导致无法接受参数，xml文件找不到参数
-keepparameternames
# 保留枚举成员及方法
-keepclassmembers enum * { *; }

# 保留用@FXML、@Inject和@PostConstruct属性标记的字段名称
-keepclassmembers class * {
  @javafx.fxml.FXML *;
  @javax.inject.Inject *;
  @javax.annotation.PostConstruct *;
}

-keepclasseswithmembernames,includedescriptorclasses class * {
    native <methods>;
}


# 忽略warn消息 打包运行异常时不要忽略，找问题
# -ignorewarnings
# 指定不打印有关配置中潜在错误或遗漏的注释，例如类名中的拼写错误或缺少可能有用的选项
-dontnote com.potato.potatotool.**
# 打印配置信息
-printconfiguration
-keep public class com.potato.potatotool.ToStart {*;}

-keep public class com.potato.potatotool.classObj.KbInfo {*;}


-keep class javafx.** {*;}
-dontwarn javafx.**
-keep class org.** {*;}
-dontwarn org.**
-keep class com.google.** {*;}
-dontwarn com.google.**
-keep class com.ibm.** {*;}
-dontwarn com.ibm.**
-keep class com.leewyatt.** {*;}
-dontwarn com.leewyatt.**
-keep class com.oracle.** {*;}
-dontwarn com.oracle.**
-keep class com.strobel.** {*;}
-dontwarn com.strobel.**
-keep class com.sun.** {*;}
-dontwarn com.sun.**
-keep class com.opencsv.** {*;}
-dontwarn com.opencsv.**
-keep class com.drew.** {*;}
-dontwarn com.drew.**
-keep class com.adobe.** {*;}
-dontwarn com.adobe.**
-keep class com.dlsc.** {*;}
-dontwarn com.dlsc.**
-keep class com.github.** {*;}
-dontwarn com.github.**
-keep class reactor.** {*;}
-dontwarn reactor.**


# -dontwarn com.potato.**

# -dontpreverify


