blockchainUrl=https://provenance.potato.gold

md5Url=https://hash.potato.gold

manifestUrlGithub=https://raw.githubusercontent.com/HotBoy-java/Resource/main/manifest.json

manifestUrlMirror=https://potato.gold/data/uploads/PotatoTool/manifest.json

pocBaseUrlPrimary=https://potato.gold/data/uploads/PotatoTool/poc/

pocBaseUrlMirror=

config=conf/config.json

bcprov=conf/bcprov.jar

testData=conf/testData.json

ip2region=conf/ip2region.xdb

commandHelp=conf/commandHelp.json

commandGeneration=conf/commandGeneration.json

taskList=conf/taskList.json

winKbInfo=conf/winKbInfo20250214.csv

bankname=conf/bankname.json

areaCode=conf/areaCode.json

shiroKey=conf/shiroKey.txt

aesKey=conf/webshellAesKey.txt

subDomains=conf/subDomains/subDomains.txt

cdnIp=conf/cdn/cdnIp.txt

cdnCname=conf/cdn/cdnCname.txt

poc=poc/

defaultUserDict=conf/dict/users.txt

defaultPassDict=conf/dict/passwords.txt

JavaStream=conf/JavaStream.js

thanks=conf/thanks.json
