aiUrl=http://221.214.4.102:50003/stream
aiUrlTest=https://192.168.3.7:8888/stream

blockchainUrl=http://potato.gold:16666

config=conf/config.json

bcprov=conf/bcprov.jar

testData=conf/testData.json

ip2region=conf/ip2region.xdb
qqwry=conf/qqwry.dat

commandHelp=conf/commandHelp.json

taskList=conf/taskList.json

winKbInfo=conf/winKbInfo20230410.csv

shiroKey=conf/shiroKey.txt

aesKey=conf/webshellAesKey.txt

poc=poc/

JavaStream=conf/JavaStream.js